apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpstests
  labels:
    app: httpstests
spec:
  selector:
    matchLabels:
      app: httpstests
      tier: web
  template:
    metadata:
      labels:
        app: httpstests
        tier: web
    spec:
      containers:
      - name: https-tests
        image: gcr.io/pi-saldum/https-tests:v1
        ports:
        - containerPort: 8081
