apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  ports:
  - port: 8081
    targetPort: 9376
  type: LoadBalancer
  loadBalancerIP: "35.246.237.70"
